# Generated by Django 5.2.9 on 2026-01-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('filiere', models.CharField(choices=[('informatique', 'Informatique'), ('gestion', 'Gestion'), ('marketing', 'Marketing')], max_length=50)),
                ('niveau', models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2')], max_length=50)),
                ('encodage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCOLARITE', 'Scolarité')], max_length=20)),
                ('email', models.EmailField(max_length=191, unique=True)),
            ],
        ),
    ]
