# Generated by Django 5.2.9 on 2026-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('matricule', models.CharField(default='TEMP', max_length=20, unique=True)),
                ('filiere', models.CharField(default='unknown', max_length=100)),
                ('niveau', models.CharField(default='unknown', max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('encodage', models.TextField()),
            ],
        ),
    ]
