# Generated by Django 5.2.9 on 2026-01-08 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_presence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], max_length=10),
        ),
    ]
