# Generated by Django 5.2.9 on 2026-01-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_etudiant_filiere_alter_etudiant_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('gestion', 'Gestion'), ('marketing', 'Marketing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2')], max_length=50),
        ),
    ]
