# Generated by Django 5.2.9 on 2026-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_alter_presence_unique_together_alter_presence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(choices=[('dsi', 'Dsi'), ('rss', 'Rss'), ('dwm', 'Dwm')], max_length=50),
        ),
    ]
